# Generated by Django 4.1.6 on 2023-03-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
