# Generated by Django 4.1.6 on 2023-03-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='type',
        ),
    ]
