# Generated by Django 4.1.6 on 2023-02-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(default='c2900cf7-a019-48f7-822a-ffa4023aba91', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
