# Generated by Django 4.1.6 on 2023-02-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0002_inbox_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='post',
            field=models.ForeignKey(default='92eb484f-8ce9-4fc7-825f-607cb72c6229', on_delete=django.db.models.deletion.CASCADE, to='epicappAPI.post'),
            preserve_default=False,
        ),
    ]
