# Generated by Django 4.1.6 on 2023-02-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0002_rename_data_post_content_remove_post_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='contentType',
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=7),
        ),
    ]
