# Generated by Django 4.1.6 on 2023-03-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0002_alter_post_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='type',
        ),
    ]
