# Generated by Django 4.1.6 on 2023-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0002_follower_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
