# Generated by Django 4.1.6 on 2023-02-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0003_rename_type_post_contenttype_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Textmarkdown'), ('text/plain', 'Textplain'), ('application/base64', 'Appimg'), ('image/png;base64', 'Pngimg'), ('image/jpeg;base64', 'Jpegimg')], max_length=18),
        ),
    ]
