# Generated by Django 4.1.6 on 2023-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0003_author_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
