# Generated by Django 4.1.6 on 2023-03-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0003_remove_author_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
