# Generated by Django 4.1.6 on 2023-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0004_comment_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
