# Generated by Django 4.1.6 on 2023-03-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0004_rename_profile_image_author_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.URLField(editable=False),
        ),
    ]
