# Generated by Django 4.1.6 on 2023-03-22 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0005_remove_inbox_content_type_alter_inbox_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='object_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('post', 'Post'), ('follow', 'Follower')], default='post', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
