# Generated by Django 4.1.6 on 2023-03-22 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0007_alter_followrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='InboxComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.URLField(editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicappAPI.post')),
            ],
        ),
    ]
