# Generated by Django 4.1.6 on 2023-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0007_alter_followrequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='object',
            field=models.URLField(default='bru', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlike',
            name='object',
            field=models.URLField(default='http://google.com', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='author',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='author',
            field=models.URLField(editable=False),
        ),
    ]
