# Generated by Django 4.1.6 on 2023-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0008_alter_follower_follower_inboxcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxcomment',
            name='id',
            field=models.URLField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
