# Generated by Django 4.1.6 on 2023-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0009_alter_inboxcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxcomment',
            name='id',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
