# Generated by Django 4.1.6 on 2023-03-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epicappAPI', '0009_like_delete_commentlike_delete_postlike'),
        ('epicappAPI', '0010_alter_inboxcomment_id'),
    ]

    operations = [
    ]
